import XCTest

import MyLibraryTests

var tests = [XCTestCaseEntry]()
tests += AdvancedTests.allTests()
tests += ArithemticTests.allTests()
tests += BindTests.allTests()
tests += ExpressionTests.allTests()
tests += FluentTests.allTests()
tests += FromTests.allTests()
tests += GroupByTests.allTests()
tests += GroupTests.allTests()
tests += HavingTests.allTests()
tests += IssueTests.allTests()
tests += JoinTests.allTests()
tests += NestedTests.allTests()
tests += NullTests.allTests()
tests += OrderByTests.allTests()
tests += QueryTests.allTests()
tests += SelectTests.allTests()
tests += SQLExpressionTests.allTests()
tests += WhereTests.allTests()
tests += WithTests.allTests()
XCTMain(tests)
