name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        images:
          - swift:5.6-focal
          - swift:5.6-bionic
          - swift:5.6-centos7
          - swift:5.6-amazonlinux2
          - swiftlang/swift:nightly-main
    container: ${{ matrix.images }}
    steps:
      - name: Workaround SPM incompatibility with old Git on CentOS 7
        if: ${{ contains(matrix.swiftos, 'centos7') }}
        run: |
          yum install -y make libcurl-devel
          git clone https://github.com/git/git -bv2.28.0 --depth 1 && cd git
          make prefix=/usr -j all install NO_OPENSSL=1 NO_EXPAT=1 NO_TCLTK=1 NO_GETTEXT=1 NO_PERL=1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Swift PM
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-${{ matrix.images }}-spm-${{ hashFiles('Package.resolved') }}-v2
          restore-keys: ${{ runner.os }}-${{ matrix.images }}-spm-
      - name: Resolve Swift dependencies
        run: swift package resolve
      - name: Build & Test
        run: swift test --enable-test-discovery --parallel --sanitize=thread

  # test-macos:
  #   name: Test macOS
  #   runs-on: macos-11
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       xcode:
  #         - latest
  #         - latest-stable
  #   steps:
  #     - name: Select toolchain
  #       uses: maxim-lobanov/setup-xcode@v1
  #       with:
  #         xcode-version: ${{ matrix.xcode }}
  #     - name: Check out Vapor
  #       uses: actions/checkout@v2
  #     - name: Run main tests with Thread Sanitizer
  #       run: |
  #         swift test --parallel --sanitize=thread \
  #           -Xlinker -rpath \
  #           -Xlinker $(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.6/macosx
