name: CI

on:
  pull_request: { branches: ["*"] }
  push: { branches: ["main"] }

jobs:
  test-linux:
    name: "Test Linux (${{ matrix.images }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        images:
          - swift:5.9-jammy
          - swift:5.9-focal
          - swift:5.9-bionic
          - swift:5.9-amazonlinux2
          - swiftlang/swift:nightly-main
    container: ${{ matrix.images }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Swift PM
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-${{ matrix.images }}-spm-${{ hashFiles('Package.resolved') }}-v4
          restore-keys: ${{ runner.os }}-${{ matrix.images }}-spm-
      - name: Resolve Swift dependencies
        run: swift package resolve
      - name: Build & Test
        run: swift test --parallel --sanitize=thread

  test-macos:
    name: "Test macOS (${{ matrix.xcode }})"
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        xcode:
          - latest-stable
          #- latest
    steps:
      - name: Select toolchain
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Swift PM
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-${{ matrix.xcode }}-spm-${{ hashFiles('Package.resolved') }}-v4
          restore-keys: ${{ runner.os }}-${{ matrix.xcode }}-spm-
      - name: Resolve Swift dependencies
        run: swift package resolve
      - name: Build & Test
        run: |
          swift test --parallel --sanitize=thread \
            -Xlinker -rpath \
            -Xlinker $(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.9/macosx
